[teams]
format = "10.60.{}.1" # Format string of teams ip address
# self_team = 43        # Your team number to avoid attacking yourself
min_team = 1  # Minimum ip number to attack
max_team = 86 # Maximum ip number to attack

[flag]
format = "[A-Z0-9]{31}=" # Regex of the flags

[farm]
password = "1234"                  # Destructive farm password
enable_api_auth = false
api_token = '00000000000000000000'

[farm.submit] # Flag submission protocol settings
system_protocol = "ructf_tcp"
system_host = "127.0.0.1"
system_port = 31337

#system_protocol="ructf_http"
#system_url="http://monitor.ructfe.org/flags"
#system_token="your_secret_token"

#system_protocol="volga_ctf"
#system_host="127.0.0.1"

#system_protocol="forcad_tcp"
#system_host="127.0.0.1"
#system_port=31337
#team_token="your_secret_token"


[farm.flag]
submit_flag_limit = 50 # The server will submit not more than SUBMIT_FLAG_LIMIT flags
submit_period = 5      # every SUBMIT_PERIOD seconds. Flags received more than
flag_lifetime = 300    # FLAG_LIFETIME seconds ago will be skipped.

[server]
host = '10.60.16.1' # Vulnbox ip address
port = 22           # Vulnbox ssh port
password = "test"   # Vulnbox ssh password

[aliases] # Alias to insert into .profile
dock = "docker-compose build --parallel --no-rm && docker-compose down --remove-orphans -t 0 && docker-compose up -d"
deploy = "echo -n $(git rev-parse HEAD) > .prev.txt && git pull && dock"
revert = "git reset --hard $(cat .prev.txt) && dock"
docker-compose = 'docker compose'

[tcpdumper]
interface = 'game'      # Interface to use for tcpdump
interval = 60           # tcpdump pcap time length
dumps_folder = ".dumps" # Where to store tcpdump's dumps

[git]
git_repo = 'git@github.com:rikyiso01/AD24-06-2022-1.git' # Git repo to push services to
ssh_key = '$HOME/.ssh/id_ed25519'                        # Path of the private key to use to push to Github

[sshkeys] # Github users of the team members to use to copy their ssh key
github_users = [
    'fabifont',
    'LorenzoGuideri',
    'gabri1135',
    'LorenzoLaCorte',
    'Samyber',
    'rikyiso01',
]
