version: '3.9'

services:
  destructivefarm:
    container_name: adserver-destructivefarm
    build:
      context: .
      dockerfile: destructivefarm/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./config.toml:/app/config.toml:ro
    environment:
      DEBUG: ${DEBUG-}
    restart: unless-stopped

  mongo:
    image: docker.io/mongo:6.0.8-jammy
    hostname: mongo
    restart: unless-stopped

  caronte:
    container_name: adserver-caronte
    hostname: caronte
    build:
      context: .
      dockerfile: caronte/Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./config.toml:/app/config.toml:ro
      - pcap:/data
    environment:
      MONGO_HOST: mongo
      DEBUG: ${DEBUG-}
    depends_on:
      - mongo
    restart: unless-stopped

  worker:
    container_name: adserver-worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    volumes:
      - ./config.toml:/app/config.toml:ro
      - pcap:/data
    environment:
      DEBUG: ${DEBUG-}
    depends_on:
      - caronte
    restart: unless-stopped

volumes:
  pcap:


networks:
  default:
    name: adserver_default
