version: '3.9'

services:
  destructivefarm:
    container_name: adserver-destructivefarm
    build:
      context: .
      dockerfile: destructivefarm/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./config.toml:/app/config.toml:ro
    restart: unless-stopped

  mongo:
    image: mongo:6.0.4-jammy
    restart: unless-stopped

  caronte:
    container_name: adserver-caronte
    build:
      context: .
      dockerfile: caronte/Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./config.toml:/opt/caronte/config.toml:ro
      - pcap:/data
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    depends_on:
      - mongo
    restart: unless-stopped

  worker:
    container_name: adserver-worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    volumes:
      - ./config.toml:/app/config.toml:ro
      - pcap:/data
    depends_on:
      - caronte
    restart: unless-stopped

volumes:
  pcap:
