on:
  release:
    types: [published]

jobs:
  release:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Prepare release Asset
        run: zip -r adserver.zip caronte destructivefarm worker .dockerignore config.example.toml docker-compose.yml poetry.lock pyproject.toml README.md
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: adserver.zip
