name: Tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
        name: Install nix
      - name: Test with pytest
        run: DOCKER_HOST='unix:///var/run/docker.sock' nix-shell --run 'poetry run python -m pytest'
